### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by bns34** [Enjoyop/coc-assets#1]
Hi. Would it be possible to get in touch with you?
Do you have Discord or any other form of contact?

**Comment by Enjoyop** [comment]
I use Discord, but I will not share it here.
If you don't mind sharing, you can write it here.

**Comment by bns34** [comment]
Nevermind. I opened this issue back when I was trying to create a Clash of Clans private server.   
I managed to get one working for clash v9 in the end.
